# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 854c319ded8e90448448cd072cfab5b474c4622bf6bf3100e27c49539fa4dc6fabd71e62ffac89eee156ee7485738c8fd012916f95cf608512fb693492b5f9f2

test:
  secret_key_base: aca658dddd6d7842db4114e1b4cd7ddafd47fe4c60d9490974a12e20c97f99131127e2c34cce6c62cda816794c96abcfed58cda1f8f725339108fd4269c6ee43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
